### ISSUE TITLE
Prefixes in phone numbers

### ISSUE THREAD

**Issue by qm3ster** [nosir/cleave.js#247] opened 2017-10-19 00:42 UTC
## Feature request
Enable prefixes in phone numbers.
The prefix behavior is perfect for country code.

**Comment by nosir** [comment] 2017-11-19 05:04
Released in v1.0.7
Cheers

**Closed by nosir** 2017-11-19 05:04 UTC
Labels: ongoing...

**Comment by lucazambon** [comment] 2017-11-24 15:52
I think this is not fixed. I'm still having trouble with **phoneRegionCode** and **Prefix**

`
var phoneFormat = new Cleave('.validate-form-input-phone', {
                phone: true,
                phoneRegionCode: 'IT',
                prefix: '+39',
                numericOnly: true
            });
`

**Comment by herivgs** [comment] 2018-02-19 16:54
I'm agree with ghost, looks like theres an issue using prefix with phone, this is my instance:
```
          var cleave = new Cleave('.cleave-input', {
                phone: true,
                prefix: '+52',
                phoneRegionCode: 'MX',
                numericOnly: true
            });
```
cleavejs v1.2.1

**Comment by nosir** [comment] 2019-03-10 11:24
Sorry, I did finally reproduce, turns out this was missing in react component, but not for the vanilla one. Fix released in https://github.com/nosir/cleave.js/releases/tag/v1.4.9
