### ISSUE TITLE
Leading zeros bring trimmed, might not always be desired behavior.

### ISSUE THREAD

**Issue by elamonta** [nosir/cleave.js#125] opened 2016-10-25 14:59 UTC
When formatting dollars, if the user enters 70,000, and wants to make it 80,000, and wants to do so by replacing the 7 by an 8.

When he does so, after removing the 7, the directive receives the new value 0,000 and trims it down to simply 0. 

In the case above, the user might want to keep the zeros and be allowed to enter the 8 in front. Could there be an option added to configure this?

**Comment by nosir** [comment] 2016-10-26 14:20
Hi @elamonta sorry, I don't think this can be configured by the lib.

Not saying it doesn't make sense, the problem is in the case above, the formatter can't partially store the number value and preserve the value `0000` or `0,000`, also don't think this will be implemented for now.

Thanks for using, will close this.

**Closed by nosir** 2016-10-26 14:20 UTC
