### ISSUE TITLE
Backspacing removes 2 characters 

### ISSUE THREAD

**Issue by ratneshraval** [nosir/cleave.js#234] opened 2017-09-22 19:24 UTC
Example cursor position: (342) 232-|
Press backspace: 
Expected result:  (342) 23|
Actual result:  (342) 2|

 options={{
            delimiters: ['(', ')', ' ', '-'],
            blocks: [0, 3, 0, 3, 4],
            numericOnly: true}}

Anyone else experiencing this?

**Comment by iamdubx** [comment] 2017-09-27 10:41
It looks like issue with space in delimeter. I have similar issue.

**Comment by nosir** [comment] 2017-10-24 12:43
Can't reproduce here: https://jsfiddle.net/qhLja8vu/1/

**Comment by nosir** [comment] 2017-11-09 11:09
Will close this, seems this got fixed with some later deployment

**Closed by nosir** 2017-11-09 11:09 UTC

**Comment by ratneshraval** [comment] 2017-11-09 18:38
Agree. Was able to verify the fix with latest version. Thank you!
