### ISSUE TITLE
Cursor jumping to end on edit with react

### ISSUE THREAD

**Issue by jlaustill** [nosir/cleave.js#280] opened 2017-12-22 16:13 UTC
http://jsbin.com/siyusux/1/edit?html,js,output

enter a longer number like 34,400.32 then try to edit at the beginning of the number and it always jumps to the end :(

**Comment by jlaustill** [comment] 2017-12-22 17:07
This [PR #262 ](https://github.com/nosir/cleave.js/pull/262) Seems to be to fix this issue, but I don't see that it was ever merged.  I'm more than happy to test and help out here if I can.

**Comment by nosir** [comment] 2018-03-14 04:09
Thanks @jlaustill A few fixes for the cursor has been merged. Would you test this? https://jsfiddle.net/nosir/kbaxx64s/
It looks good to me.

**Comment by nosir** [comment] 2018-03-16 05:02
Can't reproduce again, will close this, please let me know if you still have issue with the url above.

**Closed by nosir** 2018-03-16 05:02 UTC
