### ISSUE TITLE
Odd behavior when using backspace on a french phone number

### ISSUE THREAD

**Issue by matthieukern** [nosir/cleave.js#324] opened 2018-04-03 13:40 UTC
When I use the phone number input with a french international number, it have an odd behavior : 
`+33 6 00|` -> hit backspace, it gives `+33 6|0`, which should be `+33 60|`

I tried to find a fix, but I'm not sure of what the `Util.getPositionOffset` code does. I'm pretty sure it comes from here though, probably introduced by https://github.com/nosir/cleave.js/issues/219. 

In this method, the `oldValue` is sliced to `"+33 6 "` that is then stripped to `"+336"` with a length of `4`, and the `newValue` is sliced to `"+33 60"` and then stripped to `"+3360"`, with a length of `5`. The resulting offset is `-1`, that is applied to the cursor position, making it to be one character over on the left.

Here is a jsfiddle that reproduces the issue : https://jsfiddle.net/2ya9d0ak/1/

**Comment by qmenoret** [comment] 2018-05-02 07:39
👍

**Comment by nosir** [comment] 2018-12-16 04:17
I think it's already fixed in the this release: https://github.com/nosir/cleave.js/releases/tag/v1.3.7
Can't reproduce anymore in your jsfiddle.
Sorry for the delay I thought this is an phonelib issue.
Please feel free to open.

**Closed by nosir** 2018-12-16 04:17 UTC
