### ISSUE TITLE
Using numeralDecimalScale 6 bug

### ISSUE THREAD

**Issue by edrdesigner** [nosir/cleave.js#287] opened 2018-01-05 11:02 UTC
When you use numeralDecimalScale= 6. And input ex: 0.000006 it turns to 6e-7 or 67. When using mobile devices or mobile version

**Comment by nosir** [comment] 2018-03-16 06:04
![img_2535](https://user-images.githubusercontent.com/352617/37505934-a370b42a-293b-11e8-82fe-91f86a3f831d.png)
Hey, can't reproduce by manually input or calling `getRawValue`, can you specify what is your mobile device?
Also, if you are calling `setRawValue`, try to use string: `"0.000006"`.

**Comment by nosir** [comment] 2018-04-07 02:10
Okay, it's been a while, closing this. I think string value won't be changed.

**Closed by nosir** 2018-04-07 02:10 UTC
