### ISSUE TITLE
Android delimiter cursor not jumping bug

### ISSUE THREAD

**Issue by FoxWhite** [nosir/cleave.js#143] opened 2016-12-22 12:05 UTC
I faced this bug on Nexus devices so my guess it has to do with Android 7. Different input events perhaps?
 
When using {creditcard: true} option, the cursor fails to move with the delimiter.
For example, user types 1,2,3,4| then 5 - here comes the delimiter space and the number 5 - and the cursor stays behind the 5, like 1234 |5. So if not paying close attention to every typed character, we get 1234 6785 instead of 1234 5678, along with some frustration. The shift happens every time the delimiter occurs.

My suggestion is to force cursor forward  each time the delimiter is applied.

**Comment by FoxWhite** [comment] 2016-12-26 06:11
Found this on android 6.0.1 as well

**Comment by nosir** [comment] 2017-01-12 12:52
Hey, I tested it on Nexus5, Android 6.0.1, couldn't reproduce your issue.
Do you have this issue with the homepage creditcard demo? http://nosir.github.io/cleave.js/

**Comment by FoxWhite** [comment] 2017-01-12 14:38
@nosir main demo works fine but the React demo fails 
https://jsfiddle.net/nosir/gLLsrxxf/
(My project is in React also)

**Comment by nosir** [comment] 2017-01-13 12:14
Okay, I can reproduce it for vanilla JS component as well, seems it only happens when input `type="text"`. That's why the homepage demo is works fine.

**Comment by FoxWhite** [comment] 2017-01-13 13:20
yep, I set all my card-related inputs to type="tel" and it seems to work. Weird bug.

This solution might not be that hacky after all, considering you get a numbers mobile keyboard instead of letters, which is more convenient

**Comment by nosir** [comment] 2017-01-13 13:53
Pushed the fix, please clear your mobile cache and try again.

**Comment by FoxWhite** [comment] 2017-01-13 14:03
Good ol' setTimeout 😁
works fine now, thanks!
(I'll still go with the tel type option, though. Numeric keyboard seems much nicer in the card input)

Cheers!

**Comment by nosir** [comment] 2017-01-15 03:19
Yea, not even surprised cause it's on Android.
Closing, thanks for reporting. 👍

**Closed by nosir** 2017-01-15 03:19 UTC
Labels: bug
